### ISSUE TITLE
Create Reusable City Selector Field 

### ISSUE THREAD

**Issue by SnaYQ97** [SnaYQ97/PizzaFinder#7]
City Selector field should be auto complitable.
Should be move to Components Folder also can be in Field Direcotory.
Should be used as Component in HomePage.

**Comment by SnaYQ97** [comment]
Also should have prop label, as string prop.

**Comment by Zibi2121** [comment]
![image](https://github.com/SnaYQ97/PizzaFinder/assets/87945302/5ffb2c99-2c57-4f07-9e77-1b6d538ccd50)

There is still a problem

**Comment by Zibi2121** [comment]
The problem was solved.
